README
----------------------------------------------------
### 1.Introduction
This folder contains the course project of Getting and Cleaning Data. It includes four files:

- README.Rmd 
    - Explain the content of this repository
    
- Coodbook.Rmd 
    - Specify the variables, data and transformation

- run_analysis.r 
    - Original R Code of data cleaning
    
- tidy.txt
    - Output of cleaned data

### 2. Source of Data
The data comes from UCI Machine Learning Repository(http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones). There are 561 variables and 10299 observations in total.

This Human Activity Recognition database built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

### 3. Goal of Data Cleaning
Our goal of this task is to:

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement. 
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names. 
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
